name: macOS Briefcase build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version (e.g. 1.2.3)'
        required: true
        type: string
  push:
    tags: [ 'v*.*.*' ]

env:
  PYTHON_VERSION: '3.10'   # Torch CPU wheels require ≥3.10 on Apple Silicon

jobs:
  macos:
    runs-on: macos-14

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: macos-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml', 'requirements.txt') }}
          restore-keys: macos-pip-${{ env.PYTHON_VERSION }}-

      - name: Install system libraries
        run: brew install --quiet portaudio ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase
          python -m pip install -r requirements.txt

      - name: Resolve version
        id: ver
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VER="${{ github.event.inputs.version }}"
          else
            VER="${GITHUB_REF##*/v}"
          fi
          [[ -n "$VER" ]] || { echo "::error ::Version not determined"; exit 1; }
          echo "ver=$VER" >> "$GITHUB_OUTPUT"
          # write version into pyproject.toml
          sed -i '' -E "s/^version = \".*\"/version = \"$VER\"/" pyproject.toml

      - name: Create bundle
        run: briefcase create macOS --no-input

      - name: Build app
        run: briefcase build macOS --no-input --update-requirements

      - name: Package (ad-hoc signed DMG)
        run: briefcase package macOS --adhoc-sign --no-input

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: Transcribrr-macOS-${{ steps.ver.outputs.ver }}-${{ runner.arch }}
          path: macOS/dist/Transcribrr-${{ steps.ver.outputs.ver }}.dmg
          if-no-files-found: error
