name: "macOS Briefcase build"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Application version (e.g. 1.2.3)"
        required: true
        type: string
  push:
    tags:
      - "v*.*.*"        # ← block list notation

env:
  PYTHON_VERSION: "3.11"

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: macos-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          restore-keys: macos-pip-${{ env.PYTHON_VERSION }}-

      - name: Install system libs
        run: brew install --quiet portaudio ffmpeg

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip packaging
          python -m pip install briefcase
          python -m pip install -r requirements.txt

      - name: Resolve version
        id: ver
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VER="${{ github.event.inputs.version }}"
          else
            VER="${GITHUB_REF##*/v}"
          fi
          [[ -n "$VER" ]] || { echo "::error::Version not determined"; exit 1; }
          echo "ver=$VER" >> "$GITHUB_OUTPUT"
          sed -i '' -E "s/^version = \".*\"/version = \"$VER\"/" pyproject.toml

      - name: Inject transient transcribrr package
        run: |
          mkdir -p transcribrr
          cat > transcribrr/__init__.py <<'PY'
          from importlib import import_module as _im
          main = _im("main").main
          __all__ = ["main"]
          PY


      - name: Create bundle
        run: briefcase create macOS --no-input

      - name: Build app
        run: briefcase build macOS --no-input --update-requirements

      - name: Package (ad-hoc signed DMG)
        run: briefcase package macOS --adhoc-sign --no-input

      - uses: actions/upload-artifact@v4
        with:
          name: Transcribrr-macOS-${{ steps.ver.outputs.ver }}-${{ runner.arch }}
          path: dist/Transcribrr-${{ steps.ver.outputs.ver }}.dmg   # ← correct location
          if-no-files-found: error
