name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        uv sync --frozen --no-install-project
        uv pip install -e .
    
    - name: Run unit tests
      env:
        QT_QPA_PLATFORM: offscreen
        PYTHONPATH: ${{ github.workspace }}
      run: |
        echo "Running tests with Python ${{ matrix.python-version }}"
        # Run entire unittest suite discovered under app/tests
        uv run python -m unittest discover -v
        echo "\nTest suite completed successfully!"
    
    - name: Run linting
      if: matrix.python-version == '3.11'
      run: |
        uv run flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 app --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          *.log
          test-results/
        retention-days: 7
